%[text] # Gravity 🧹
%[text] 
%[text] An interactive gravity and physics simulation embedded in MATLAB.
%[text:tableOfContents]{"heading":"Table of Contents"}
%[text] 
%%
%[text] ## Overview
%[text] 
%[text] This toolbox demonstrates how to embed a web application (HTML/CSS/JavaScript)
%[text] inside a MATLAB desktop app using the **uihtml** component.
%[text] 
%%
%[text] ## Quick Start
%[text] 
%[text] Launch the app by running:
%[text] 
%[text] ```matlabCodeExample
%[text] gravityApp
%[text] ```
%[text] 
%[text] Or run the code cell below:
gravityApp
%[text] 
%%
%[text] ## Features
%[text] - Record the trajectory with the main flight simulator \
gravityFlightSimulator
%%
%[text] - Post-process the results with the \
gravityFlightDashboard
%%
%[text] ## How It Works
%[text] 
%[text] The app uses MATLAB's `uihtml` component to embed a web-based physics simulation inside a `uifigure` window. 
%[text] 
%%
%[text] ## Technical Details
%[text] 
%[text] The main components are:
%[text] 
%[text:table]
%[text] | File | Description |
%[text] | --- | --- |
%[text] | `gravityFlightSimulator.m` | Flight simulator based on uihtml to bring ThreeJS 3D graphics |
%[text] | `gravityFlightDashboard.m` | Post processing the trajectories generated by the app |
%[text] | `dist/index.html` | HTML entry point with relative asset paths |
%[text] | `dist/assets/` | JavaScript and CSS files |
%[text:table]
%[text] 
%%
%[text] ## Learn More
%[text] [skills/skills/matlab-uihtml-app-builder/SKILL.md at main · matlab/skills · GitHub](https://github.com/matlab/skills/blob/main/skills/matlab-uihtml-app-builder/SKILL.md)

%[appendix]{"version":"1.0"}
%---
%[metadata:view]
%   data: {"layout":"inline","rightPanelPercent":40}
%---
